### ISSUE TITLE
适配问题，以及滑动问题

### ISSUE THREAD

**Issue by sanduom** [7449/SlideView#1]
我仿照您的代码写了一遍，基本思路也理清了，SlideView，Adapter，等都没有问题，但是在滑动后，感觉是ViewHolder出现了问题，只要一滑动，就会变成一个item占据一个屏幕，后面就不管怎么滑动都是这样了，再有一个就是适配问题，适配到屏幕小的手机上面时，SlideView会变
<br />![image](https://cloud.githubusercontent.com/assets/17918101/18240980/587d4a80-7381-11e6-89e7-85d57db6516e.png)
<br />

**Comment by 7449** [comment]
@sanduom 问题已经解决 代码同步了，至于滑动item占据一个屏幕我并没有发现，不知道是什么问题。。。

**Comment by sanduom** [comment]
我找到了item占据一个屏幕是我item根布局height写成了match，但是我不明白为什么在第一次现实的时候，既然我设置的时候错了，可他还是正确显示的，反而在滑动后才会变化？
